---
- hosts: all
  become: yes
  roles:
    - role: geerlingguy.mysql
    - role: geerlingguy.apache
    - role: geerlingguy.php
    - role: frock81.arwp
      tags: wordpress
  tasks:
    - debug: msg="Test message"
