---
# For Geerlingguy.mysql
mysql_databases:
  - name: wordpress
mysql_users:
  - name: wordpress
    host: '%'
    password: wordpress
    priv: '*.*:ALL'

# # For Geerlingguy.apache.
apache_vhosts:
  - servername: "wp17.local"
    documentroot: /opt/wordpress

# For Geerlingguy.php with apache.
php_packages:
  - libapache2-mod-php
  - php-mysql
  - php-apcu

arwp_wpconfig_siteurl: http://wp17.local

arwp_blog_download_creates: ""