---
# For Geerlingguy.mysql
mysql_databases:
  - name: wordpress
mysql_users:
  - name: wordpress
    host: '%'
    password: wordpress
    priv: '*.*:ALL'

# For Geerlingguy.apache.
apache_vhosts:
  - servername: "wp17.local"
    documentroot: /opt/wordpress

# For Geerlingguy.php with apache.
php_packages:
  - libapache2-mod-php
  - php-mysql
  - php-apcu

# Required for arwp.
arwp_wpconfig_siteurl: http://wp17.local

# arwp_blog_download_creates: ""
# arwp_wordpress_version: "5.1.1"

# arwp_wordpress_sync_wp_content: true

arwp_plugins:
  - slug: woocommerce
    version: 3.6.4
  - slug: wp-mail-smtp
    version: 1.4.2
